server:
  port: 8888

spring:
  profiles:
    active: pull-mode

---

spring:
  profiles: pull-mode
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xaynk/SpringCloudRepo