server.port: 8888

spring.profiles.active: push-mode

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

---
spring.profiles: push-mode

spring:
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/Users/zkay0001/Projects/Dev/csihome-springcloud-config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring.profiles: pull-mode

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xaynk/SpringCloudRepo
